### ISSUE TITLE
BTC private key to address and balance check

### ISSUE THREAD

**Issue by Handsomekaizer** [aridaybordon/check-bitcoin-balance#1]
Hello sir 
I just stumbled on these your GitHub repo I was looking for a program that will help me convert my compressed private key to address and check the balance. Could you please help me update or create a python program that will help me convert my compressed private key to address and check the balance. The reason I needed this was to scan through a massive private key txt file and see if I can find my missing 10 characters private key. Please help me if I recover the wallet I will donate some BTC to you. Thanks

**Comment by aridaibordon** [comment]
Greetings Handsomekaizer,

Thanks for your feedback!

I have updated the code to allow checking balance from private keys. To use
it, just add your private keys to the address.txt file, create a main.py
file and run the following code:

from bitcoin_balance import get_total_balance

balance = get_total_balance(return_usd=True, private_key=True)
print(balance)

balance will return a dictionary with all the private keys and the balance
inside each one.
